### ISSUE TITLE
Got Installation error.

### ISSUE THREAD

**Issue by tuxxon** [anishathalye/neural-style#165]
Hello.

I got the following error when running `pip3 install -r requirements.txt`.

```
ERROR: Could not find a version that satisfies the requirement tensorflow-gpu<2.0,>=1.0 (from -r requirements.txt (line 4)) (from versions: 2.2.0rc1, 2.2.0rc2, 2.2.0rc3, 2.2.0rc4, 2.2.0, 2.3.0rc0)
ERROR: No matching distribution found for tensorflow-gpu<2.0,>=1.0 (from -r requirements.txt (line 4))
```

Can you help me resolve this?
Interestingly, when using pip3 install `tensorflow-gpu`, v2.2.0 has been installed on ubuntu20.04 - wsl2.

----
Gordon Ahn.

**Comment by anishathalye** [comment]
neural-style requires pre-2.0 `tensorflow-gpu`. You can see the full release history here: https://pypi.org/project/tensorflow-gpu/#history. Maybe there is no <2.0 release for WSL or something? Are you using a GPU? If not, you can try pip install `tensorflow<2.0,>=1.0`.

**Comment by tuxxon** [comment]
WSL2https://docs.microsoft.com/en-us/windows/wsl/install-win10

**Comment by anishathalye** [comment]
Yes, I'm aware of WSL, I just don't use Windows so I am not deeply familiar with any incompatibilities between WSL and a "real" (native) Linux installation. The code seems to [work](https://travis-ci.com/github/anishathalye/neural-style/) in its current state on Ubuntu 16.04 (Xenial), so that's why I'm guessing it's a problem with WSL or your setup.

Hope you get it sorted out, and please let us know if you find any useful troubleshooting info that we can incorporate into the readme.
