### ISSUE TITLE
TO MANY FILES

### ISSUE THREAD

**Issue by raayraay69** [anishathalye/neural-style#167]
When i am running this code in the terminal i get error code:

(base) a@Erics-MacBook-Pro ~ % floyd run --gpu --env tensorflow-1.3 --data floydhub/datasets/imagenet-vgg-verydeep-19/3:vgg "python neural_style.py --network /vgg/imagenet-vgg-verydeep-19.mat --content <content file> --styles <style file> --output <output file>"
Directory contains too many files to upload. If you have data files in the current directory, please upload them separately using "floyd data" command and remove them from here.
See http://docs.floydhub.com/faqs/job/#i-get-too-many-open-files-error-when-i-run-my-project for more details on how to fix this.
  I am not sure why this is happening if you could direct me to solution that would be great, Thanks.

**Comment by anishathalye** [comment]
I don't really know anything about running this on FloydHub, I have never used it. The info in the README came from #121.

**Comment by raayraay69** [comment]
Yes i tried the orignal code you posted but i only get 'System Exit 2' with no output

**Comment by anishathalye** [comment]
Do you have Python, TensorFlow, etc. installed correctly? What happens if you run `python neural_style.py --help`

**Comment by jwrubel** [comment]
I'm the author of #121 - it's been a couple of years and I don't have floydhub set up anymore but if you can paste the full command you're using here maybe that would help. Your original post shows `floyd run --gpu --env tensorflow-1.3 --data floydhub/datasets/imagenet-vgg-verydeep-19/3:vgg "python neural_style.py --network /vgg/imagenet-vgg-verydeep-19.mat --content --styles <style file> --output "` - are you entering the path and name of an image you use as the content paramter and giving it an output filename? I can see where if you passed the `--content` argument without a filename, the `neural_style.py` script would error with `SystemExit 2` because it can't parse the arguments, and floydhub would give `Too many files` because it would assume you are trying to upload your entire local directory. 

If you pass an argument for the content image and give it an output filename and that still doesn't work, try using Floydhub's [style transfer tutorial](https://docs.floydhub.com/examples/style_transfer/) and see if that one works?

**Comment by raayraay69** [comment]
Ok, i am very knew to this website but it seems promising to run this code. SO i need 1 file (names for the output) for the code to work correctly. <using the above code you provided?>

**Comment by jwrubel** [comment]
That should be correct. If you have an image in the same directory named `myimage.jpg`, you _should_ be able to get this working by entering `floyd run --gpu --env tensorflow-1.3 --data floydhub/datasets/imagenet-vgg-verydeep-19/3:vgg "python neural_style.py --network /vgg/imagenet-vgg-verydeep-19.mat --content myimage.jpg --styles <style file> --output myimage-withstyles.jpg"`. You would just need to replace the `myimage.jpg` after the `--content` argument with your actual photo and make sure the argument for `--styles` is correct. Then if the process works, your restyled photo would be `myimage-withstyles.jpg` or whatever you typed for the `--output` argument.

**Comment by raayraay69** [comment]
Ok, i wanted to leave a direction for people uploading the data set on floyd hub

1.Download dataset givne from user anishathalye (Requirements
Data Files
Pre-trained VGG network (MD5 106118b7cf60435e6d8e04f6a6dc3657) - put it in the top level of this repository, or specify its location using the --network option.
)
2. https://www.youtube.com/watch?v=relTVr694Ko watch video on how to upload this dataset on floydhub and make project 

3. There is common misconception about what mount does. Here is a forum https://github.com/floydhub/floyd-docs/issues/53#issuecomment-325482487

4. run project

**Comment by raayraay69** [comment]
hope this can help future user with your code

**Comment by anishathalye** [comment]
Thanks for giving an update on how you got the data set upload to work.
