### ISSUE TITLE
problem loading mat file

### ISSUE THREAD

**Issue by gosha1128** [anishathalye/neural-style#4]
Hi, I get the following error in vgg.py:

Traceback (most recent call last):
  File "/Users/cuongwilliams/Packages/neural-style/neural_style.py", line 122, in <module>
    main()
  File "/Users/cuongwilliams/Packages/neural-style/neural_style.py", line 108, in main
    checkpoint_iterations=options.checkpoint_iterations)
  File "/Users/cuongwilliams/Packages/neural-style/stylize.py", line 24, in stylize
    net, mean_pixel = vgg.net(network, image)
  File "/Users/cuongwilliams/Packages/neural-style/vgg.py", line 24, in net
    mean = data['normalization'][0][0][0]
KeyError: 'normalization'

Any thoughts what I might be doing wrong ?  I do use the --network parameter to specify the location of the mat file.

**Comment by anishathalye** [comment]
Uhh... not sure, I've never seen that happen before. Did you make sure to download [this file](http://www.vlfeat.org/matconvnet/models/imagenet-vgg-verydeep-19.mat)?

**Comment by gosha1128** [comment]
I downloaded the one provided by the link at the end of your readme.  Also
I'm on a Mac ...

**Comment by gosha1128** [comment]
Do you use Linux or Windows ?

**Comment by anishathalye** [comment]
I'm on a Mac.

If there's no `normalization` key... what's the value of `data` at that line in the code?

**Comment by anishathalye** [comment]
I've also run this on Linux btw. And this seems to have something to do with `scipy.io.loadmat`, which shouldn't have anything to do with the platform.

**Comment by gosha1128** [comment]
OK I tried on Linux Ubuntu and same problem.  'data' is valid - I added a print statement in vgg.py.  If I print the keys, there is no 'normalization' key:

['layers', '__version__', 'meta', '__header__', '__globals__']
Traceback (most recent call last):
  File "/home/gwilliams/Packages/neural-style/github/neural-style//neural_style.py", line 122, in <module>
    main()
  File "/home/gwilliams/Packages/neural-style/github/neural-style//neural_style.py", line 108, in main
    checkpoint_iterations=options.checkpoint_iterations)
  File "/home/gwilliams/Packages/neural-style/github/neural-style/stylize.py", line 24, in stylize
    net, mean_pixel = vgg.net(network, image)
  File "/home/gwilliams/Packages/neural-style/github/neural-style/vgg.py", line 24, in net
    mean = data['normalization'][0][0][0]
KeyError: 'normalization'

**Comment by gosha1128** [comment]
Do you know your version of scipy ?

**Comment by anishathalye** [comment]
```
>>> scipy.__version__
'0.16.1'
```

**Comment by cloitre** [comment]
Hello,
I am running into the same issue.
I am on Ubuntu 14.04, 64 bits, using scipy 0.13.3.

**Comment by anishathalye** [comment]
Oh wow, weird. Maybe it's an issue with older versions of SciPy?

**Comment by gosha1128** [comment]
With some difficulty, I upgrade to scipy to 0.16 and it still doesn't work
for me (ubuntu 14.04).

I'm now installing MATLAB and saving the mat file in a different way...wish
me luck...

**Comment by anishathalye** [comment]
Huh, that's really weird. I haven't had problems with it on Ubuntu 14.04 or Mac OS X. I've also had a couple friends try this, and they haven't had issues.

If I print the keys, I get: `['layers', '__header__', '__globals__', 'classes', '__version__', 'normalization']`

**Comment by cloitre** [comment]
I don't know how to print the keys with python so I looked at the mat file on matlab.
The 'normalization' structure is under a key called 'meta'.
By changing the code to include this change, I get rid of the previous error, but get a new one.

Line of code changed:
from:     mean = data['normalization'][0][0][0]
to:    mean = data['meta']['normalization'][0][0][0]

Error received after the change:
Traceback (most recent call last):
  File "neural_style.py", line 122, in <module>
    main()
  File "neural_style.py", line 108, in main
    checkpoint_iterations=options.checkpoint_iterations)
  File "/home/smart/Documents/ConvNet/neural-style/stylize.py", line 24, in stylize
    net, mean_pixel = vgg.net(network, image)
  File "/home/smart/Documents/ConvNet/neural-style/vgg.py", line 24, in net
    mean_pixel = np.mean(mean, axis=(0, 1))
  File "/usr/local/lib/python2.7/dist-packages/numpy/core/fromnumeric.py", line 2874, in mean
    out=out, keepdims=keepdims)
  File "/usr/local/lib/python2.7/dist-packages/numpy/core/_methods.py", line 56, in _mean
    rcount = _count_reduce_items(arr, axis)
  File "/usr/local/lib/python2.7/dist-packages/numpy/core/_methods.py", line 50, in _count_reduce_items
    items *= arr.shape[ax]
IndexError: tuple index out of range

It seams that it relates to the way the mean_pixel variable is calculated, at the following line.
I tried to change the 'axis' option to 'axis=(1, 2)' instead of 'axis=(0, 1)', but the error remained.

**Comment by anishathalye** [comment]
Oh wow, apparently the issue is that the MatConvNet people changed their data format...

See http://www.vlfeat.org/matconvnet/pretrained/#older-file-versions

The file that I was linking to has moved here: http://www.vlfeat.org/matconvnet/models/beta16/imagenet-vgg-verydeep-19.mat

I'll update the README for now, but at some point, the code should probably be updated for the new version.

**Comment by anishathalye** [comment]
My version: `MD5 (imagenet-vgg-verydeep-19.mat) = 8ee3263992981a1d26e73b3ca028a123`

The current version: `MD5 (imagenet-vgg-verydeep-19.mat) = b9b4a9eb1c2fb3b50e1ec1aca6f22342`

**Comment by anishathalye** [comment]
Oh wait. The link to the "old version" is broken - they're still serving the new version... :/

**Comment by cloitre** [comment]
The link you provided two messages ago seems to work for me.

Audren Cloitre
PhD candidate in Mechanical Engineering
77 Massachusetts Avenue
Office 5-423
Cambridge, MA, 02139
617-256-6975
________________________________________

**Comment by anishathalye** [comment]
Oh whoops, yeah, you're right, that link works. I must have mixed it up when checking to see if it is correct.

Okay, updating the readme now.

**Comment by gosha1128** [comment]
Confirmed.  That also worked for me.  Thanks for being so quick about this.

FYI...I'm getting over 10X speedup on my Tesla GPU as well.

( Note:  I also had to downgrade to numpy 1.1 because recent versions don't
have numpy.matmul defined, which is used in vgg.py )

I may try porting this to Torch7 to see if I can get any more speedup....

**Comment by anishathalye** [comment]
Btw, there's already a pretty fast Torch implementation: https://github.com/jcjohnson/neural-style/
(I think it's 2-3x faster than the TensorFlow implementation, cause TF is kinda slow right now)

**Comment by gosha1128** [comment]
Excellent thanks !  BTW, do you have any tips on using style-scales ?  What
does it do ?

-g

**Comment by anishathalye** [comment]
Here are some demos: http://ktsiegel.com/neural-style-web/

**Comment by anishathalye** [comment]
Just play around with stuff till it looks nice :)

**Comment by gosha1128** [comment]
Wow - you weren't kidding - the torch implementation is very fast...

**Comment by exowanderer** [comment]
Hello!

I'm only signing in to say thank you for the conversation.  After downloading the "old" version of the .mat file, the routine is running as well as could be expected. 

This was an excellent dialogue that really helped understand both the code, as well as how good github can really work!

Thank you!

**Comment by anishathalye** [comment]
Glad to see you found it useful! (Also, glad to see that people look through closed issues before opening new ones 😛)

**Comment by JLansey** [comment]
I had the same issue since I just googled and downloaded the new mat file. Now things are running! Very cool, thanks so much.

**Comment by anishathalye** [comment]
Wait, what? There's no need to use Google -- just use the file that's linked in the README.

**Comment by JLansey** [comment]
Yes you are absolutely right - I'm a doofus for googling instead of just reading the instructions.
